# Generated by Django 4.0.4 on 2022-06-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_panier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier',
            old_name='article',
            new_name='articles',
        ),
    ]
